/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletests;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public class Libro {
        private String nombre;
        private String autor;
    public Libro(String nombre, String autor) {
        this.nombre = nombre;
        this.autor = autor;
    }
    public String getNombre() {
        return nombre;
    }
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAutor() {
        return autor;
    }
    public void setCorreo(String correo) {
        this.autor = correo;
    }
}

    public class Biblioteca {
        ArrayList<Libro> libros = new ArrayList<Libro>();


        public Biblioteca() {
            libros = new ArrayList<Libro>();
        }
        public String getNombre(int i) {
            return libros.get(i).getNombre();
        }
        public String getCorreo(int i) {
            return libros.get(i).getAutor();
        }


        public ArrayList<Libro> anadirLibros(Libro libro) {
            libros.add(libro);
            return libros;
        }

        public ArrayList<Libro> eliminarLibros(String name1) {
            int x = 0;
            int bucle = 0;
            String name = name1;
            while (bucle < libros.size()) {
                if (libros.get(x).nombre == name) {
                    libros.remove(x);
                } else {
                    x++;
                }
            }
            return libros;
        }

        public ArrayList<Libro> llistar_llibres() {
            int bucle = 0;
            while (bucle < libros.size()) {
                System.out.println(libros.get(bucle));
                bucle++;
            }
            return libros;
        }
    }

    public class Usuario {
        private String nombre;
        private String correo;
        public Usuario(String nombre, String correo) {
            this.nombre = nombre;
            this.correo = correo;
        }
        public String getNombre() {
            return nombre;
        }
        public void setNombre(String nombre) {
            this.nombre = nombre;
        }
        public String getCorreo() {
            return correo;
        }
        public void setCorreo(String correo) {
            this.correo = correo;
        }
    }

    public class Usuarios {
        private static ArrayList<Usuario> usuarios;

        public Usuarios() {
            usuarios = new ArrayList<Usuario>();
        }
        public String getNombre(int i) {
            return usuarios.get(i).getNombre();
        }
        public String getCorreo(int i) {
            return usuarios.get(i).getCorreo();
        }

        public ArrayList<Usuario> anadirUsuario(Usuario usuario) {
            usuarios.add(usuario);
            return usuarios;
        }
        public void verUsuario(Usuario usuario) {
            for(int x = 0; x < usuarios.size(); x++){
              usuarios.get(x);
              System.out.print(usuarios.get(x).getNombre() + " ");
              System.out.print(usuarios.get(x).getCorreo());
            }
            
        }

        public ArrayList<Usuario> eliminarUsuario(String name1) {
            int x = 0;
            int bucle = 0;
            String name = name1;
            while (bucle < usuarios.size()) {
                if (usuarios.get(x).getNombre() == name) {
                    usuarios.remove(x);
                } else {
                    x++;
                }
            }
            return usuarios;
        }

        public static ArrayList<Usuario> getUsuarios() {
            return usuarios;
        }
    }

    public class Lecturas {
        HashMap<Object, ArrayList<Libro>> leidos;
        
        public Lecturas(){
            leidos = new HashMap<>();
        }
        public HashMap<Object, ArrayList<Libro>> AnadirLibro(ArrayList<Libro> libro, Object usuario){
            leidos.put(usuario, libro);
            return leidos;
        }
        public ArrayList<Libro> getLibrosLeidos(String usuario) {
            return leidos.get(usuario);
        }
    }
}
