/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletests;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App.Usuario usuario= new App.Usuario("nombre", "correo");
    
    }
}
